import os, re

# Definition of the 15 articles with metadata
articles = [
    {
        "filename": "spiderman-brand-new-day.md",
        "slug": "spiderman-brand-new-day",
        "title": "Spider-Man Brand New Day Review: $2.4B MCU Record",
        "category": "Hollywood",
        "date": "2026-09-27",
        "image": "/images/spiderman-brand-new-day-box-office-mcu-review.webp",
        "imageAlt": "Spider-Man Brand New Day banner featuring Tom Holland swinging over Manhattan",
        "desc": "Spider-Man Brand New Day review analyzing Tom Holland $2.4B box office record, Destin Daniel Cretton direction, and Phase 6 MCU implications.",
        "movie_name": "Spider-Man: Brand New Day",
        "director": "Destin Daniel Cretton",
        "cast": "Tom Holland, Zendaya, Sadie Sink, Mark Ruffalo, Michael Mando",
        "budget": "$220 Million",
        "box_office": "$2.41 Billion Worldwide",
        "external_link": "[IMDb Official](https://www.imdb.com/title/tt20235688/)",
        "ext_label": "IMDb",
        "internal_refs": [
            ("/avengers-endgame-encore-review", "Avengers Endgame Encore"),
            ("/the-vvaan-movie-review", "The Vvaan Force of the Forest"),
            ("/september-2026-box-office-clash", "September 2026 weekend box office clash"),
            ("/mirzapur-the-movie-box-office", "Mirzapur The Movie")
        ],
        "core_topic": "Spider-Man Brand New Day represents Marvel Studios most ambitious street-level and multiverse hybrid following the memory wipe finale of No Way Home."
    },
    {
        "filename": "the-vvaan-movie-review.md",
        "slug": "the-vvaan-movie-review",
        "title": "The Vvaan Movie Review: Sidharth Action Spectacle",
        "category": "Bollywood",
        "date": "2026-09-26",
        "image": "/images/the-vvaan-force-of-the-forrest-sidharth-malhotra-review.webp",
        "imageAlt": "The Vvaan Force of the Forrest banner showing Sidharth Malhotra in mystical ancient ruins",
        "desc": "The Vvaan movie review detailing Sidharth Malhotra action heroism, Tamannaah Bhatia, folk mythology, and opening weekend box office.",
        "movie_name": "The Vvaan: Force of the Forest",
        "director": "Deepak Mishra",
        "cast": "Sidharth Malhotra, Tamannaah Bhatia, Jaideep Ahlawat, Ashutosh Rana",
        "budget": "₹110 Crore",
        "box_office": "₹43.80 Crore (Opening Weekend India)",
        "external_link": "[Bollywood Hungama](https://www.bollywoodhungama.com/)",
        "ext_label": "Bollywood Hungama",
        "internal_refs": [
            ("/mirzapur-the-movie-box-office", "Mirzapur The Movie"),
            ("/hunkkaar-the-roar-review", "Hunkkaar The Roar"),
            ("/the-paradise-movie-review", "The Paradise"),
            ("/september-2026-box-office-clash", "September 2026 box office report")
        ],
        "core_topic": "The Vvaan Force of the Forest blends Central Indian tribal folklore with large-scale action choreography and environmental mysticism."
    },
    {
        "filename": "mirzapur-the-movie-box-office.md",
        "slug": "mirzapur-the-movie-box-office",
        "title": "Mirzapur The Movie Box Office: ₹328 Crore Triumph",
        "category": "Bollywood",
        "date": "2026-09-27",
        "image": "/images/mirzapur-the-movie-box-office-record-328-crore-analysis.webp",
        "imageAlt": "Mirzapur The Movie banner showing Kaleen Bhaiya, Guddu Pandit, and Munna Tripathi",
        "desc": "Mirzapur The Movie box office collection report analyzing ₹328 crore milestone, Pankaj Tripathi, Ali Fazal, and Hindi cinema theatrical records.",
        "movie_name": "Mirzapur: The Movie",
        "director": "Gurmmeet Singh",
        "cast": "Pankaj Tripathi, Ali Fazal, Divyenndu Sharma, Shweta Tripathi, Rasika Dugal",
        "budget": "₹95 Crore",
        "box_office": "₹328.60 Crore Worldwide Gross",
        "external_link": "[Box Office India](https://www.boxofficeindia.com/)",
        "ext_label": "Box Office India",
        "internal_refs": [
            ("/the-vvaan-movie-review", "The Vvaan"),
            ("/shaque-netflix-review", "Shaque Trust No One"),
            ("/toxic-yash-movie-review", "Toxic A Fairytale for Grown-Ups"),
            ("/september-2026-box-office-clash", "weekend collection clash")
        ],
        "core_topic": "Mirzapur The Movie demonstrates how streaming franchises can transition into dominant silver screen commercial juggernauts."
    },
    {
        "filename": "hunkkaar-the-roar-review.md",
        "slug": "hunkkaar-the-roar-review",
        "title": "Hunkkaar The Roar Review: Gritty Courtroom Drama",
        "category": "Bollywood",
        "date": "2026-09-26",
        "image": "/images/hunkkaar-the-roar-aneet-padda-courtroom-drama-review.webp",
        "imageAlt": "Hunkkaar The Roar banner highlighting Aneet Padda in intense courtroom debate",
        "desc": "Hunkkaar The Roar review analyzing Aneet Padda performance, realistic courtroom drama, box office figures, and critical reception.",
        "movie_name": "Hunkkaar: The Roar",
        "director": "Sudhir Sharma",
        "cast": "Aneet Padda, Kumud Mishra, Yashpal Sharma, Seema Biswas",
        "budget": "₹28 Crore",
        "box_office": "₹14.85 Crore (Opening Weekend India)",
        "external_link": "[Variety India](https://variety.com/)",
        "ext_label": "Variety",
        "internal_refs": [
            ("/mirzapur-the-movie-box-office", "Mirzapur The Movie"),
            ("/the-vvaan-movie-review", "The Vvaan Force of the Forest"),
            ("/shaque-netflix-review", "Shaque on Netflix"),
            ("/september-2026-box-office-clash", "September 25 theatrical releases")
        ],
        "core_topic": "Hunkkaar The Roar delivers a grounded legal procedural examining custodial corruption and institutional accountability in North India."
    },
    {
        "filename": "the-paradise-movie-review.md",
        "slug": "the-paradise-movie-review",
        "title": "The Paradise Movie Review: Nani Action Blockbuster",
        "category": "South Cinema",
        "date": "2026-09-26",
        "image": "/images/the-paradise-nani-srikanth-odela-box-office-review.webp",
        "imageAlt": "The Paradise banner featuring Natural Star Nani in vintage 1980s rebel attire",
        "desc": "The Paradise movie review and box office analysis detailing Nani fiery performance, Srikanth Odela direction, and Telugu cinema records.",
        "movie_name": "The Paradise",
        "director": "Srikanth Odela",
        "cast": "Nani, Mohan Babu, Kayadu Lohar, Jisshu Sengupta",
        "budget": "₹80 Crore",
        "box_office": "₹68.50 Crore Worldwide (4 Days)",
        "external_link": "[Track Tollywood](https://tracktollywood.com/)",
        "ext_label": "Track Tollywood",
        "internal_refs": [
            ("/toxic-yash-movie-review", "Toxic A Fairytale for Grown-Ups"),
            ("/agadha-telugu-movie-review", "Agadha on ZEE5"),
            ("/the-vvaan-movie-review", "The Vvaan"),
            ("/september-2026-box-office-clash", "September box office clash")
        ],
        "core_topic": "The Paradise showcases Natural Star Nani in a raw period action avatar examining trade union rebellions in 1980s Andhra Pradesh."
    },
    {
        "filename": "toxic-yash-movie-review.md",
        "slug": "toxic-yash-movie-review",
        "title": "Toxic Movie Review: Rocking Star Yash Visceral Epic",
        "category": "South Cinema",
        "date": "2026-09-26",
        "image": "/images/toxic-a-fairytale-for-grown-ups-yash-box-office-review.webp",
        "imageAlt": "Toxic A Fairytale for Grown-Ups poster with Yash in double-breasted suit",
        "desc": "Toxic movie review analyzing Rocking Star Yash transformational performance, Geetu Mohandas direction, and ₹214.50 Cr opening records.",
        "movie_name": "Toxic: A Fairytale for Grown-Ups",
        "director": "Geetu Mohandas",
        "cast": "Yash, Nayanthara, Kiara Advani, Huma Qureshi, Shruti Haasan",
        "budget": "₹175 Crore",
        "box_office": "₹214.50 Crore Worldwide Opening Weekend",
        "external_link": "[Filmibeat](https://www.filmibeat.com/)",
        "ext_label": "Filmibeat",
        "internal_refs": [
            ("/the-paradise-movie-review", "The Paradise"),
            ("/spiderman-brand-new-day", "Spider-Man Brand New Day"),
            ("/september-2026-box-office-clash", "weekend box office records"),
            ("/agadha-telugu-movie-review", "Agadha")
        ],
        "core_topic": "Toxic A Fairytale for Grown-Ups elevates Indian gangster storytelling into European noir art through Yash magnetic anti-hero screen presence."
    },
    {
        "filename": "agadha-telugu-movie-review.md",
        "slug": "agadha-telugu-movie-review",
        "title": "Agadha Telugu Movie Review: MS Raju ZEE5 Thriller",
        "category": "South Cinema",
        "date": "2026-09-26",
        "image": "/images/agadha-telugu-supernatural-thriller-zee5-review.webp",
        "imageAlt": "Agadha Telugu supernatural thriller banner showing misty colonial manor at midnight",
        "desc": "Agadha movie review analyzing MS Raju taut direction, chilling psychological horror atmosphere, cast performances, and ZEE5 streaming numbers.",
        "movie_name": "Agadha",
        "director": "MS Raju",
        "cast": "Naveen Chandra, Nandita Swetha, Ajay Ghosh, Rohini",
        "budget": "₹15 Crore",
        "box_office": "Over 8.4 Million Streaming Hours on ZEE5",
        "external_link": "[ZEE5 Streaming](https://www.zee5.com/)",
        "ext_label": "ZEE5",
        "internal_refs": [
            ("/the-paradise-movie-review", "The Paradise"),
            ("/toxic-yash-movie-review", "Toxic A Fairytale for Grown-Ups"),
            ("/shaque-netflix-review", "Shaque Trust No One"),
            ("/dont-be-shy-review", "Don't Be Shy on Prime Video")
        ],
        "core_topic": "Agadha reinvents Telugu supernatural horror through ancestral guilt, psychological trauma, and nuanced atmospheric sound design."
    },
    {
        "filename": "shaque-netflix-review.md",
        "slug": "shaque-netflix-review",
        "title": "Shaque Netflix Review: Parineeti Mystery Thriller",
        "category": "OTT & Web Series",
        "date": "2026-09-26",
        "image": "/images/shaque-trust-no-one-parineeti-chopra-netflix-review.webp",
        "imageAlt": "Shaque Trust No One banner featuring Parineeti Chopra in London precinct",
        "desc": "Shaque Trust No One Netflix review analyzing Parineeti Chopra psychological performance, mystery plot twists, and global streaming viewership.",
        "movie_name": "Shaque: Trust No One",
        "director": "Ribhu Dasgupta",
        "cast": "Parineeti Chopra, Harleen Sethi, Jennifer Winget, Rajit Kapur",
        "budget": "₹45 Crore",
        "box_office": "Top 10 Global Non-English Title on Netflix",
        "external_link": "[Netflix Media Center](https://about.netflix.com/)",
        "ext_label": "Netflix",
        "internal_refs": [
            ("/dont-be-shy-review", "Don't Be Shy"),
            ("/agadha-telugu-movie-review", "Agadha"),
            ("/mirzapur-the-movie-box-office", "Mirzapur The Movie"),
            ("/hunkkaar-the-roar-review", "Hunkkaar The Roar")
        ],
        "core_topic": "Shaque Trust No One delivers a tightly coiled psychological whodunit investigating maternal grief and institutional complicity across London."
    },
    {
        "filename": "dont-be-shy-review.md",
        "slug": "dont-be-shy-review",
        "title": "Don't Be Shy Review: Prime Video Coming-of-Age Hit",
        "category": "OTT & Web Series",
        "date": "2026-09-26",
        "image": "/images/dont-be-shy-prime-video-series-season-1-review.webp",
        "imageAlt": "Don't Be Shy Prime Video banner featuring students on campus amphitheater",
        "desc": "Don't Be Shy Season 1 review analyzing Prime Video vibrant young adult drama, relatable comedy, character dynamics, and streaming impact.",
        "movie_name": "Don't Be Shy (Season 1)",
        "director": "Kabir Mehta",
        "cast": "Tanya Maniktala, Rohit Saraf, Mihir Ahuja, Revathi Pillai",
        "budget": "₹22 Crore",
        "box_office": "Trending #2 Worldwide on Prime Video",
        "external_link": "[Amazon Prime Video](https://www.primevideo.com/)",
        "ext_label": "Prime Video",
        "internal_refs": [
            ("/shaque-netflix-review", "Shaque Trust No One"),
            ("/primetime-movie-review", "Primetime on A24"),
            ("/hunkkaar-the-roar-review", "Hunkkaar The Roar"),
            ("/agadha-telugu-movie-review", "Agadha on ZEE5")
        ],
        "core_topic": "Don't Be Shy treats youth social anxiety and modern urban collegiate friendships with emotional honesty, buoyant humor, and sharp writing."
    },
    {
        "filename": "avengers-endgame-encore-review.md",
        "slug": "avengers-endgame-encore-review",
        "title": "Avengers Endgame Encore Review: New Footage Guide",
        "category": "Cinema News",
        "date": "2026-09-26",
        "image": "/images/avengers-endgame-encore-september-2026-new-footage-breakdown.webp",
        "imageAlt": "Avengers Endgame Encore banner with Thanos, Iron Man, and Doctor Doom rift",
        "desc": "Avengers Endgame Encore theatrical review analyzing the 4-minute additions, TVA Loki sequence, Doctor Doom setup, and box office impact.",
        "movie_name": "Avengers: Endgame - Encore Edition",
        "director": "Anthony and Joe Russo",
        "cast": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Josh Brolin",
        "budget": "$356 Million (Original)",
        "box_office": "$2.82 Billion Cumulative Worldwide",
        "external_link": "[Marvel Official](https://www.marvel.com/movies)",
        "ext_label": "Marvel",
        "internal_refs": [
            ("/spiderman-brand-new-day", "Spider-Man Brand New Day"),
            ("/september-2026-box-office-clash", "September 25 global box office clash"),
            ("/heart-of-the-beast-review", "Heart of the Beast"),
            ("/forgotten-island-movie-review", "Forgotten Island")
        ],
        "core_topic": "Avengers Endgame Encore theatrical event re-release bridges Phase 3 nostalgia directly into the Robert Downey Jr Doctor Doom saga of Phase 6."
    },
    {
        "filename": "september-2026-box-office-clash.md",
        "slug": "september-2026-box-office-clash",
        "title": "September 2026 Box Office Clash: Global Records Shattered",
        "category": "Cinema News",
        "date": "2026-09-27",
        "image": "/images/september-2026-fourth-weekend-box-office-clash-records.webp",
        "imageAlt": "September 25-27 weekend box office report banner with gold financial charts",
        "desc": "September 25-27 2026 box office clash report analyzing massive global theatrical revenues, Marvel milestones, Bollywood surges, and South Indian records.",
        "movie_name": "September 25-27 Weekend Theatrical Slate",
        "director": "Multiple Studios",
        "cast": "Tom Holland, Yash, Sidharth Malhotra, Pankaj Tripathi, Brad Pitt",
        "budget": "$850 Million Cumulative Industry Slate",
        "box_office": "$480 Million Global Weekend Turnstile",
        "external_link": "[Box Office Mojo](https://www.boxofficemojo.com/)",
        "ext_label": "Box Office Mojo",
        "internal_refs": [
            ("/spiderman-brand-new-day", "Spider-Man Brand New Day"),
            ("/toxic-yash-movie-review", "Toxic A Fairytale for Grown-Ups"),
            ("/mirzapur-the-movie-box-office", "Mirzapur The Movie"),
            ("/the-vvaan-movie-review", "The Vvaan Force of the Forest")
        ],
        "core_topic": "The historic September 25-27 weekend generated unprecedented theatrical revenues worldwide through an unprecedented blend of blockbusters."
    },
    {
        "filename": "forgotten-island-movie-review.md",
        "slug": "forgotten-island-movie-review",
        "title": "Forgotten Island Review: DreamWorks Animated Triumph",
        "category": "Movie Reviews",
        "date": "2026-09-26",
        "image": "/images/forgotten-island-dreamworks-animated-movie-review.webp",
        "imageAlt": "Forgotten Island animation banner showing lush tropical archipelago and floating spirits",
        "desc": "Forgotten Island movie review and animation breakdown detailing Joel Crawford direction, H.E.R. and Liza Soberano voice acting, and box office.",
        "movie_name": "Forgotten Island",
        "director": "Joel Crawford",
        "cast": "H.E.R., Liza Soberano, Manny Jacinto, Dante Basco, Lea Salonga",
        "budget": "$115 Million",
        "box_office": "$38.2 Million Opening Weekend (North America)",
        "external_link": "[DreamWorks Animation](https://www.dreamworks.com/)",
        "ext_label": "DreamWorks",
        "internal_refs": [
            ("/spiderman-brand-new-day", "Spider-Man Brand New Day"),
            ("/heart-of-the-beast-review", "Heart of the Beast"),
            ("/primetime-movie-review", "Primetime"),
            ("/september-2026-box-office-clash", "September 25 weekend releases")
        ],
        "core_topic": "Forgotten Island brings Southeast Asian mythology to vivid life through innovative painterly watercolor CG animation and rich folk traditions."
    },
    {
        "filename": "heart-of-the-beast-review.md",
        "slug": "heart-of-the-beast-review",
        "title": "Heart of the Beast Review: Brad Pitt Action Drama",
        "category": "Movie Reviews",
        "date": "2026-09-26",
        "image": "/images/heart-of-the-beast-brad-pitt-david-ayer-movie-review.webp",
        "imageAlt": "Heart of the Beast banner featuring Brad Pitt with tactical rifle in Alaskan snow",
        "desc": "Heart of the Beast movie review and box office analysis detailing Brad Pitt rugged performance, David Ayer direction, and Alaskan wilderness survival.",
        "movie_name": "Heart of the Beast",
        "director": "David Ayer",
        "cast": "Brad Pitt, Michael Shannon, Jeffrey Wright, Garret Dillahunt",
        "budget": "$85 Million",
        "box_office": "$24.8 Million Opening Weekend",
        "external_link": "[Deadline Hollywood](https://deadline.com/)",
        "ext_label": "Deadline",
        "internal_refs": [
            ("/primetime-movie-review", "Primetime"),
            ("/resident-evil-2026-review", "Resident Evil 2026"),
            ("/forgotten-island-movie-review", "Forgotten Island"),
            ("/september-2026-box-office-clash", "weekend box office receipts")
        ],
        "core_topic": "Heart of the Beast pairs Brad Pitt and David Ayer in a visceral, tactile wilderness warfare survival thriller set in sub-zero Alaska."
    },
    {
        "filename": "primetime-movie-review.md",
        "slug": "primetime-movie-review",
        "title": "Primetime Movie Review: Robert Pattinson A24 Drama",
        "category": "Hollywood",
        "date": "2026-09-26",
        "image": "/images/primetime-robert-pattinson-a24-movie-review-analysis.webp",
        "imageAlt": "Primetime A24 movie banner featuring Robert Pattinson under studio television broadcast monitors",
        "desc": "Primetime movie review and psychological analysis detailing Robert Pattinson sensational turn as Chris Hansen, Lance Oppenheim direction, and Venice premiere.",
        "movie_name": "Primetime",
        "director": "Lance Oppenheim",
        "cast": "Robert Pattinson, Brian Cox, Lakeith Stanfield, Cristin Milioti",
        "budget": "$35 Million",
        "box_office": "$22,400 Per-Theater Average (Platform Release)",
        "external_link": "[A24 Films](https://a24films.com/)",
        "ext_label": "A24",
        "internal_refs": [
            ("/resident-evil-2026-review", "Resident Evil 2026"),
            ("/heart-of-the-beast-review", "Heart of the Beast"),
            ("/dont-be-shy-review", "Don't Be Shy"),
            ("/spiderman-brand-new-day", "Spider-Man Brand New Day")
        ],
        "core_topic": "Primetime dissects 2000s reality investigative television through Robert Pattinson electrifying, morally bankrupt portrayal of media showmanship."
    },
    {
        "filename": "resident-evil-2026-review.md",
        "slug": "resident-evil-2026-review",
        "title": "Resident Evil 2026 Review: Zach Cregger Horror Hit",
        "category": "Hollywood",
        "date": "2026-09-25",
        "image": "/images/resident-evil-2026-zach-cregger-horror-movie-review.webp",
        "imageAlt": "Resident Evil 2026 banner featuring shadowy medical lab corridor with biohazard lights",
        "desc": "Resident Evil 2026 movie review detailing Zach Cregger horror reinvention, Austin Abrams performance, Raccoon City dread, and box office success.",
        "movie_name": "Resident Evil (2026)",
        "director": "Zach Cregger",
        "cast": "Austin Abrams, Georgina Campbell, David Jonsson, Justin Long",
        "budget": "$45 Million",
        "box_office": "$62.40 Million Worldwide Opening Weekend",
        "external_link": "[Bloody Disgusting](https://bloody-disgusting.com/)",
        "ext_label": "Bloody Disgusting",
        "internal_refs": [
            ("/primetime-movie-review", "Primetime"),
            ("/heart-of-the-beast-review", "Heart of the Beast"),
            ("/spiderman-brand-new-day", "Spider-Man Brand New Day"),
            ("/agadha-telugu-movie-review", "Agadha")
        ],
        "core_topic": "Resident Evil strips away Hollywood superhero action to restore the slow-burn survival horror and claustrophobia of original 1996 video game roots."
    }
]

print(f"Configured {len(articles)} articles with short slugs and 50-60 character titles.")
